name: Go test

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        microservice: [
          image-service,
          ingredient-service,
          instruction-service,
          metadata-service,
          recipe-service
        ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.20

    - name: Build
      working-directory: ${{ matrix.microservice }}
      run: go build -v cmd/${{ matrix.microservice }}/main.go

    - name: Test
      uses: robherley/go-test-action@v0.4.1
      with:
        moduleDirectory: ${{ matrix.microservice }}
